llm_provider: "ollama"

# Ollama settings
ollama_base_url: "http://localhost:11434"
ollama_model_name: "llama3.1"

# Gemini settings
gemini_api_key: "your-google-api-key-here"
gemini_model_name: "gemini-1.5-flash"

# Paths
cpp_repo_path: "data/TritonRoute-WXL"
paper_path: "data/paper.pdf"
output_path: "data/output"
chroma_db_path: "data/chroma_db"

# Processing Settings
max_function_lines: 100
min_function_lines: 5
chunk_size: 1000
chunk_overlap: 200
embedding_model: "all-MiniLM-L6-v2"

# Documentation Settings
include_complexity_analysis: true
include_citations: true
max_doc_length: 2000
